import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

async function main() {
  const airplanes = [
    { modelNumber: "Boeing 747-8", capacity: 467 },
    { modelNumber: "Airbus A380", capacity: 544 },
    { modelNumber: "Boeing 777-300ER", capacity: 365 },
    { modelNumber: "Airbus A350-900", capacity: 325 },
    { modelNumber: "Boeing 787-9", capacity: 290 },
    { modelNumber: "Airbus A320neo", capacity: 180 },
    { modelNumber: "Boeing 737 MAX 8", capacity: 178 },
    { modelNumber: "Embraer E190", capacity: 100 },
    { modelNumber: "Bombardier CRJ900", capacity: 86 },
    { modelNumber: "ATR 72", capacity: 78 },
    { modelNumber: "Boeing 767-300ER", capacity: 219 },
    { modelNumber: "Airbus A330-300", capacity: 299 },
    { modelNumber: "Boeing 757-200", capacity: 200 },
    { modelNumber: "Airbus A319neo", capacity: 156 },
    { modelNumber: "Boeing 737-800", capacity: 189 },
    { modelNumber: "Embraer 195", capacity: 124 },
    { modelNumber: "Bombardier CS300", capacity: 145 },
    { modelNumber: "Airbus A220-300", capacity: 160 },
    { modelNumber: "Boeing 737 MAX 9", capacity: 180 },
    { modelNumber: "Airbus A321neo", capacity: 230 },
    { modelNumber: "Boeing 777X", capacity: 426 },
    { modelNumber: "Airbus A350-1000", capacity: 369 },
    { modelNumber: "Boeing 787-10", capacity: 330 },
    { modelNumber: "Embraer E175", capacity: 88 },
    { modelNumber: "Bombardier CRJ200", capacity: 50 },
    { modelNumber: "Embraer ERJ-145", capacity: 50 },
    { modelNumber: "Bombardier Challenger 350", capacity: 10 },
    { modelNumber: "Gulfstream G650", capacity: 13 },
    { modelNumber: "Cessna Citation X", capacity: 8 },
    { modelNumber: "Dassault Falcon 7X", capacity: 12 },
    { modelNumber: "Boeing 777F", capacity: 102 },
    { modelNumber: "Airbus A330F", capacity: 70 },
    { modelNumber: "Boeing 767F", capacity: 58 },
    { modelNumber: "Antonov An-124", capacity: 120 },
    { modelNumber: "Lockheed C-130 Hercules", capacity: 92 },
    { modelNumber: "C-17 Globemaster III", capacity: 102 },
    { modelNumber: "Airbus A400M Atlas", capacity: 110 },
    { modelNumber: "Boeing P-8 Poseidon", capacity: 9 },
    { modelNumber: "Lockheed Martin F-35", capacity: 1 },
    { modelNumber: "Sukhoi Su-35", capacity: 1 },
    { modelNumber: "Boeing F/A-18 Super Hornet", capacity: 1 },
    { modelNumber: "Eurofighter Typhoon", capacity: 1 },
    { modelNumber: "Dassault Rafale", capacity: 1 },
    { modelNumber: "Airbus Beluga", capacity: 2 },
    { modelNumber: "Antonov An-225", capacity: 88 },
    { modelNumber: "Boeing Dreamlifter", capacity: 2 },
    { modelNumber: "Airbus A300-600ST Beluga", capacity: 2 },
    { modelNumber: "Learjet 75", capacity: 8 },
    { modelNumber: "HondaJet", capacity: 4 },
    { modelNumber: "HAL Tejas", capacity: 1 },
    { modelNumber: "Sukhoi Su-30MKI", capacity: 1 },
    { modelNumber: "MiG-29", capacity: 1 },
    { modelNumber: "Mitsubishi F-2", capacity: 1 },
    { modelNumber: "Pilatus PC-21", capacity: 2 },
    { modelNumber: "HAL Dhruv", capacity: 2 },
    { modelNumber: "Mi-17", capacity: 24 },
    { modelNumber: "Kamov Ka-52", capacity: 2 },
    { modelNumber: "Kawasaki P-1", capacity: 10 },
    { modelNumber: "Pilatus PC-6", capacity: 8 },
    { modelNumber: "HAL Light Combat Helicopter", capacity: 1 },
    { modelNumber: "Sukhoi Su-57", capacity: 1 },
    { modelNumber: "Mitsubishi X-2 Shinshin", capacity: 1 },
    { modelNumber: "Pilatus PC-7", capacity: 2 },
    { modelNumber: "HAL LCA Navy", capacity: 1 },
    { modelNumber: "MiG-31", capacity: 2 },
    { modelNumber: "Kawasaki C-2", capacity: 12 },
    { modelNumber: "Pilatus PC-12", capacity: 9 },
    { modelNumber: "HAL LCH", capacity: 1 },
    { modelNumber: "Tupolev Tu-160", capacity: 16 },
    { modelNumber: "Mitsubishi F-15J", capacity: 1 },
    { modelNumber: "Pilatus PC-9", capacity: 2 },
    { modelNumber: "HAL HTT-40", capacity: 2 },
    { modelNumber: "MiG-35", capacity: 1 },
  ];

  const cities = [
    { id: 1, name: "Andhra Pradesh", code: "AP" },
    { id: 2, name: "Arunachal Pradesh", code: "AR" },
    { id: 3, name: "Assam", code: "AS" },
    { id: 4, name: "Bihar", code: "BR" },
    { id: 5, name: "Chhattisgarh", code: "CG" },
    { id: 6, name: "Goa", code: "GA" },
    { id: 7, name: "Gujarat", code: "GJ" },
    { id: 8, name: "Haryana", code: "HR" },
    { id: 9, name: "Himachal Pradesh", code: "HP" },
    { id: 10, name: "Jharkhand", code: "JH" },
    { id: 11, name: "Karnataka", code: "KA" },
    { id: 12, name: "Kerala", code: "KL" },
    { id: 13, name: "Madhya Pradesh", code: "MP" },
    { id: 14, name: "Maharashtra", code: "MH" },
    { id: 15, name: "Manipur", code: "MN" },
    { id: 16, name: "Meghalaya", code: "ML" },
    { id: 17, name: "Mizoram", code: "MZ" },
    { id: 18, name: "Nagaland", code: "NL" },
    { id: 19, name: "Odisha", code: "OD" },
    { id: 20, name: "Punjab", code: "PB" },
    { id: 21, name: "Rajasthan", code: "RJ" },
    { id: 22, name: "Sikkim", code: "SK" },
    { id: 23, name: "Tamil Nadu", code: "TN" },
    { id: 24, name: "Telangana", code: "TS" },
    { id: 25, name: "Tripura", code: "TR" },
    { id: 26, name: "Uttar Pradesh", code: "UP" },
    { id: 27, name: "Uttarakhand", code: "UK" },
    { id: 28, name: "West Bengal", code: "WB" },
    { id: 29, name: "Andaman and Nicobar Islands", code: "AN" },
    { id: 30, name: "Chandigarh", code: "CH" },
    { id: 31, name: "Dadra and Nagar Haveli and Daman and Diu", code: "DNHDD" },
    { id: 32, name: "Delhi", code: "DL" },
    { id: 33, name: "Jammu and Kashmir", code: "JK" },
    { id: 34, name: "Ladakh", code: "LA" },
    { id: 35, name: "Lakshadweep", code: "LD" },
    { id: 36, name: "Puducherry", code: "PY" },
  ];

  const airports = [
    {
      id: 1,
      name: "Visakhapatnam International Airport",
      code: "VTZ",
      address: "Visakhapatnam, Andhra Pradesh",
      cityId: 1,
    },
    {
      id: 2,
      name: "Donyi Polo Airport",
      code: "HGI",
      address: "Itanagar, Arunachal Pradesh",
      cityId: 2,
    },
    {
      id: 3,
      name: "Lokpriya Gopinath Bordoloi International Airport",
      code: "GAU",
      address: "Guwahati, Assam",
      cityId: 3,
    },
    {
      id: 4,
      name: "Dibrugarh Airport",
      code: "DIB",
      address: "Dibrugarh, Assam",
      cityId: 3,
    },
    {
      id: 5,
      name: "Jay Prakash Narayan International Airport",
      code: "PAT",
      address: "Patna, Bihar",
      cityId: 4,
    },
    {
      id: 6,
      name: "Gaya International Airport",
      code: "GAY",
      address: "Gaya, Bihar",
      cityId: 4,
    },
    {
      id: 7,
      name: "Swami Vivekananda Airport",
      code: "RPR",
      address: "Raipur, Chhattisgarh",
      cityId: 5,
    },
    {
      id: 8,
      name: "Goa International Airport (Dabolim)",
      code: "GOI",
      address: "Dabolim, Goa",
      cityId: 6,
    },
    {
      id: 9,
      name: "Manohar International Airport",
      code: "GOX",
      address: "Mopa, Goa",
      cityId: 6,
    },
    {
      id: 10,
      name: "Sardar Vallabhbhai Patel International Airport",
      code: "AMD",
      address: "Ahmedabad, Gujarat",
      cityId: 7,
    },
    {
      id: 11,
      name: "Vadodara Airport",
      code: "BDQ",
      address: "Vadodara, Gujarat",
      cityId: 7,
    },
    {
      id: 12,
      name: "Kangra Airport",
      code: "DHM",
      address: "Kangra, Himachal Pradesh",
      cityId: 9,
    },
    {
      id: 13,
      name: "Birsa Munda Airport",
      code: "IXR",
      address: "Ranchi, Jharkhand",
      cityId: 10,
    },
    {
      id: 14,
      name: "Kempegowda International Airport",
      code: "BLR",
      address: "Bangalore, Karnataka",
      cityId: 11,
    },
    {
      id: 15,
      name: "Cochin International Airport",
      code: "COK",
      address: "Kochi, Kerala",
      cityId: 12,
    },
    {
      id: 16,
      name: "Devi Ahilya Bai Holkar Airport",
      code: "IDR",
      address: "Indore, Madhya Pradesh",
      cityId: 13,
    },
    {
      id: 17,
      name: "Chhatrapati Shivaji Maharaj International Airport",
      code: "BOM",
      address: "Mumbai, Maharashtra",
      cityId: 14,
    },
    {
      id: 18,
      name: "Imphal International Airport",
      code: "IMF",
      address: "Imphal, Manipur",
      cityId: 15,
    },
    {
      id: 19,
      name: "Shillong Airport",
      code: "SHL",
      address: "Shillong, Meghalaya",
      cityId: 16,
    },
    {
      id: 20,
      name: "Lengpui Airport",
      code: "AJL",
      address: "Aizawl, Mizoram",
      cityId: 17,
    },
    {
      id: 21,
      name: "Dimapur Airport",
      code: "DMU",
      address: "Dimapur, Nagaland",
      cityId: 18,
    },
    {
      id: 22,
      name: "Biju Patnaik International Airport",
      code: "BBI",
      address: "Bhubaneswar, Odisha",
      cityId: 19,
    },
    {
      id: 23,
      name: "Sri Guru Ram Dass Jee International Airport",
      code: "ATQ",
      address: "Amritsar, Punjab",
      cityId: 20,
    },
    {
      id: 24,
      name: "Jaipur International Airport",
      code: "JAI",
      address: "Jaipur, Rajasthan",
      cityId: 21,
    },
    {
      id: 25,
      name: "Pakyong Airport",
      code: "PYG",
      address: "Pakyong, Sikkim",
      cityId: 22,
    },
    {
      id: 26,
      name: "Chennai International Airport",
      code: "MAA",
      address: "Chennai, Tamil Nadu",
      cityId: 23,
    },
    {
      id: 27,
      name: "Rajiv Gandhi International Airport",
      code: "HYD",
      address: "Hyderabad, Telangana",
      cityId: 24,
    },
    {
      id: 28,
      name: "Maharaja Bir Bikram Airport",
      code: "IXA",
      address: "Agartala, Tripura",
      cityId: 25,
    },
    {
      id: 29,
      name: "Chaudhary Charan Singh International Airport",
      code: "LKO",
      address: "Lucknow, Uttar Pradesh",
      cityId: 26,
    },
    {
      id: 30,
      name: "Jolly Grant Airport",
      code: "DED",
      address: "Dehradun, Uttarakhand",
      cityId: 27,
    },
    {
      id: 31,
      name: "Netaji Subhas Chandra Bose International Airport",
      code: "CCU",
      address: "Kolkata, West Bengal",
      cityId: 28,
    },
    {
      id: 32,
      name: "Veer Savarkar International Airport",
      code: "IXZ",
      address: "Port Blair, Andaman and Nicobar Islands",
      cityId: 29,
    },
    {
      id: 33,
      name: "Shaheed Bhagat Singh International Airport",
      code: "IXC",
      address: "Chandigarh",
      cityId: 30,
    },
    {
      id: 34,
      name: "Indira Gandhi International Airport",
      code: "DEL",
      address: "New Delhi, Delhi",
      cityId: 32,
    },
    {
      id: 35,
      name: "Sheikh ul-Alam International Airport",
      code: "SXR",
      address: "Srinagar, Jammu and Kashmir",
      cityId: 33,
    },
    {
      id: 36,
      name: "Kushok Bakula Rimpochee Airport",
      code: "IXL",
      address: "Leh, Ladakh",
      cityId: 34,
    },
    {
      id: 37,
      name: "Agatti Airport",
      code: "AGX",
      address: "Agatti Island, Lakshadweep",
      cityId: 35,
    },
    {
      id: 38,
      name: "Puducherry Airport",
      code: "PNY",
      address: "Puducherry",
      cityId: 36,
    },
  ];

  await prisma.airplane.createMany({
    data: airplanes,
  });

  await prisma.city.createMany({
    data: cities,
  });

  await prisma.airport.createMany({
    data: airports,
  });
}

main()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async (e) => {
    console.error(e);
    await prisma.$disconnect();
    process.exit(1);
  });
